databaseType = "MySql"
id = "1384f2a8-4e01-40db-b2bf-76b2c0e161b8"
name = "Encom"

[environments.default]
password = "Flyway123"
url = "jdbc:mysql://localhost:3306/EncomDb?useSSL=false&allowPublicKeyRetrieval=true"
user = "flyway"

[flyway]
locations = [ "filesystem:sql" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flyway.check]
majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"