CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    ProfilePictureUrl VARCHAR(255) DEFAULT '',
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);